/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.Random;
import Database.DatabaseConnection;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author fikra
 */
public class DashboardUser extends JFrame {
    private int assigneeId;
    private JPanel activityPanelDetails;
    /**
     * Creates new form DashboardUser
     */
    public DashboardUser(int assigneeId) {
        this.assigneeId = assigneeId;
        setTitle("Dashboard");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(1366, 768);
        setLayout(new BorderLayout());
        initComponents();
        
        
        activityPanel.setLayout(new BoxLayout(activityPanel, BoxLayout.Y_AXIS));
        activityPanel.setBorder(new EmptyBorder(10, 10, 150, 10)); // top, left, bottom, right
        recentActivityLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        
        //TxtDahboard
        TxtDashboard.setOpaque(true);
        TxtDashboard.setBackground(new java.awt.Color(211, 211, 211));
        TxtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TxtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            TxtDashboard.setBackground(new java.awt.Color(191, 191, 191));
        }
        
        public void mouseExited(java.awt.event.MouseEvent evt) {
        TxtDashboard.setBackground(new java.awt.Color(211, 211, 211));
        }
        });
        
        // TxtProject
        TxtProject.setOpaque(true);
        TxtProject.setBackground(new java.awt.Color(211, 211, 211));
        TxtProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtProject.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
        TxtProject.setBackground(new java.awt.Color(191, 191, 191));
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
        TxtProject.setBackground(new java.awt.Color(211, 211, 211));
        }
        });

        // TxtTask
        TxtTask.setOpaque(true);
        TxtTask.setBackground(new java.awt.Color(211, 211, 211));
        TxtTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtTask.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
        TxtTask.setBackground(new java.awt.Color(191, 191, 191));
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
        TxtTask.setBackground(new java.awt.Color(211, 211, 211));
        }
        });
        
        // TxtLogout
        TxtLogout.setOpaque(true);
        TxtLogout.setBackground(new java.awt.Color(211, 211, 211));
        TxtLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtLogout.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
        TxtLogout.setBackground(new java.awt.Color(191, 191, 191));
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
        TxtLogout.setBackground(new java.awt.Color(211, 211, 211));
        }
        });
        
        loadTaskSummary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContent = new javax.swing.JPanel();
        OverdueTask1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        recentPoints = new javax.swing.JLabel();
        TotalUser1 = new javax.swing.JPanel();
        taskAssignLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TotalTask1 = new javax.swing.JPanel();
        taskOverdueLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        taskInProgressPanel = new javax.swing.JPanel();
        taskInProgressLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        activityPanel = new javax.swing.JPanel();
        recentActivityLabel = new javax.swing.JLabel();
        TopUser1 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        totalPoints = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        SidebarPanel = new javax.swing.JPanel();
        TxtDashboard = new javax.swing.JLabel();
        TxtProject = new javax.swing.JLabel();
        TxtLogout = new javax.swing.JLabel();
        TxtTask = new javax.swing.JLabel();
        LineSidebar = new javax.swing.JSeparator();
        LineSidebar1 = new javax.swing.JSeparator();
        LogoArasaka = new javax.swing.JLabel();
        TxtArasaka = new javax.swing.JLabel();
        TxtSocialMedia = new javax.swing.JLabel();
        TxtProjectManagement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainContent.setBackground(new java.awt.Color(12, 44, 71));

        OverdueTask1.setBackground(new java.awt.Color(171, 203, 202));

        txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt1.setText("RECENT POINT");

        recentPoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recentPoints.setText("No Recent Points");

        javax.swing.GroupLayout OverdueTask1Layout = new javax.swing.GroupLayout(OverdueTask1);
        OverdueTask1.setLayout(OverdueTask1Layout);
        OverdueTask1Layout.setHorizontalGroup(
            OverdueTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverdueTask1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(OverdueTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recentPoints)
                    .addComponent(txt1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OverdueTask1Layout.setVerticalGroup(
            OverdueTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverdueTask1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recentPoints)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        TotalUser1.setBackground(new java.awt.Color(214, 201, 197));

        taskAssignLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        taskAssignLabel.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("TASK");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("ASSIGN");

        javax.swing.GroupLayout TotalUser1Layout = new javax.swing.GroupLayout(TotalUser1);
        TotalUser1.setLayout(TotalUser1Layout);
        TotalUser1Layout.setHorizontalGroup(
            TotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalUser1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(taskAssignLabel)
                .addGap(42, 42, 42))
            .addGroup(TotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TotalUser1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel17)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        TotalUser1Layout.setVerticalGroup(
            TotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalUser1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(taskAssignLabel)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalUser1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(42, 42, 42))
            .addGroup(TotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TotalUser1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel17)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        TotalTask1.setBackground(new java.awt.Color(214, 201, 197));

        taskOverdueLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        taskOverdueLabel.setText("0");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("TASK");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setText("OVERDUE");

        javax.swing.GroupLayout TotalTask1Layout = new javax.swing.GroupLayout(TotalTask1);
        TotalTask1.setLayout(TotalTask1Layout);
        TotalTask1Layout.setHorizontalGroup(
            TotalTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalTask1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(taskOverdueLabel)
                .addGap(42, 42, 42))
            .addGroup(TotalTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TotalTask1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel30)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        TotalTask1Layout.setVerticalGroup(
            TotalTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalTask1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(taskOverdueLabel)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalTask1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(42, 42, 42))
            .addGroup(TotalTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TotalTask1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel30)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        taskInProgressPanel.setBackground(new java.awt.Color(214, 201, 197));

        taskInProgressLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        taskInProgressLabel.setText("0");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setText("TASK IN");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setText("PROGRESS");

        javax.swing.GroupLayout taskInProgressPanelLayout = new javax.swing.GroupLayout(taskInProgressPanel);
        taskInProgressPanel.setLayout(taskInProgressPanelLayout);
        taskInProgressPanelLayout.setHorizontalGroup(
            taskInProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskInProgressPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(taskInProgressLabel)
                .addGap(42, 42, 42))
            .addGroup(taskInProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taskInProgressPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel33)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
        taskInProgressPanelLayout.setVerticalGroup(
            taskInProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskInProgressPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(taskInProgressLabel)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskInProgressPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(42, 42, 42))
            .addGroup(taskInProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taskInProgressPanelLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel33)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        activityPanel.setBackground(new java.awt.Color(214, 201, 197));

        recentActivityLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recentActivityLabel.setText("RECENT ACTIVITY");

        javax.swing.GroupLayout activityPanelLayout = new javax.swing.GroupLayout(activityPanel);
        activityPanel.setLayout(activityPanelLayout);
        activityPanelLayout.setHorizontalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(recentActivityLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        activityPanelLayout.setVerticalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recentActivityLabel)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        TopUser1.setBackground(new java.awt.Color(171, 203, 202));

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel90.setText("USERS");

        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel92.setText("Name");

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel93.setText("Total Points");

        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel95.setText("Role");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText(": entongeuy@gmail.com");

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel98.setText("Email");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText(": Entong");

        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel97.setText(": assignee");

        totalPoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalPoints.setText(": 10");

        javax.swing.GroupLayout TopUser1Layout = new javax.swing.GroupLayout(TopUser1);
        TopUser1.setLayout(TopUser1Layout);
        TopUser1Layout.setHorizontalGroup(
            TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUser1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopUser1Layout.createSequentialGroup()
                        .addComponent(jLabel90)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TopUser1Layout.createSequentialGroup()
                        .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel92)
                            .addComponent(jLabel98)
                            .addComponent(jLabel95)
                            .addComponent(jLabel93))
                        .addGap(66, 66, 66)
                        .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPoints)
                            .addComponent(emailLabel)
                            .addComponent(nameLabel)
                            .addComponent(jLabel97))
                        .addGap(0, 189, Short.MAX_VALUE))))
        );
        TopUser1Layout.setVerticalGroup(
            TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUser1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel98)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel95)
                    .addComponent(jLabel97))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(totalPoints))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContentLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainContentLayout.createSequentialGroup()
                        .addComponent(TotalUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(taskInProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(TotalTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainContentLayout.createSequentialGroup()
                        .addComponent(TopUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OverdueTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(activityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskInProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TopUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OverdueTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(activityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        greeting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        greeting.setText("Hello, {user}! Here's what happening today");

        SidebarPanel.setBackground(new java.awt.Color(211, 211, 211));
        SidebarPanel.setPreferredSize(new java.awt.Dimension(220, 420));

        TxtDashboard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icondashboard.png"))); // NOI18N
        TxtDashboard.setText("DASHBOARD");
        TxtDashboard.setIconTextGap(15);

        TxtProject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconproject.png"))); // NOI18N
        TxtProject.setText("PROJECT");
        TxtProject.setIconTextGap(15);
        TxtProject.setInheritsPopupMenu(false);
        TxtProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtProjectMouseClicked(evt);
            }
        });

        TxtLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconlogout.png"))); // NOI18N
        TxtLogout.setText("LOGOUT");
        TxtLogout.setIconTextGap(15);
        TxtLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtLogoutMouseClicked(evt);
            }
        });

        TxtTask.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icontask.png"))); // NOI18N
        TxtTask.setText("TASK");
        TxtTask.setIconTextGap(15);
        TxtTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTaskMouseClicked(evt);
            }
        });

        LineSidebar.setForeground(new java.awt.Color(0, 0, 0));

        LineSidebar1.setForeground(new java.awt.Color(0, 0, 0));

        LogoArasaka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconarasaka.png"))); // NOI18N

        TxtArasaka.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        TxtArasaka.setText("Arasaka");

        TxtSocialMedia.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        TxtSocialMedia.setText("Social Media ");

        TxtProjectManagement.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        TxtProjectManagement.setText("Project Management");

        javax.swing.GroupLayout SidebarPanelLayout = new javax.swing.GroupLayout(SidebarPanel);
        SidebarPanel.setLayout(SidebarPanelLayout);
        SidebarPanelLayout.setHorizontalGroup(
            SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPanelLayout.createSequentialGroup()
                .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LineSidebar)
                            .addComponent(LineSidebar1)))
                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtProject, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTask, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(TxtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SidebarPanelLayout.createSequentialGroup()
                                .addComponent(LogoArasaka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                                        .addComponent(TxtArasaka, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(TxtSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SidebarPanelLayout.createSequentialGroup()
                                .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SidebarPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(TxtProjectManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        SidebarPanelLayout.setVerticalGroup(
            SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoArasaka)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarPanelLayout.createSequentialGroup()
                        .addComponent(TxtArasaka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSocialMedia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtProjectManagement)
                .addGap(76, 76, 76)
                .addComponent(TxtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LineSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtProject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LineSidebar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greeting)
                    .addComponent(MainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(greeting)
                .addGap(24, 24, 24)
                .addComponent(MainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(SidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtProjectMouseClicked
        AssigneProject project = new AssigneProject(assigneeId);
        project.setVisible(true);
        this.dispose(); // Menutup form saat ini jika perlu
    }//GEN-LAST:event_TxtProjectMouseClicked

    private void TxtLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure want to exit?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm ==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_TxtLogoutMouseClicked

    private void TxtTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTaskMouseClicked

        AssigneTask task = new AssigneTask(assigneeId);
        task.setVisible(true);
        this.dispose(); // Menutup form saat ini jika perlu
    }//GEN-LAST:event_TxtTaskMouseClicked

    private void loadTaskSummary() {
        try (Connection conn = DatabaseConnection.getConnection()) {
            
            //nama user header
            String queryUserHeaderName = "SELECT name FROM assignees WHERE id = ? ";
            PreparedStatement stmtUserHeaderName = conn.prepareStatement(queryUserHeaderName);
            stmtUserHeaderName.setInt(1, assigneeId);
            ResultSet rsUserHeaderName = stmtUserHeaderName.executeQuery();
            if (rsUserHeaderName.next()){
                String username = rsUserHeaderName.getString("name");
                greeting.setText("Hello, " + username +" Here's what happening today");
                
            }
            rsUserHeaderName.close();
            stmtUserHeaderName.close();
            
            // Task Assign
            String queryAssign = "SELECT COUNT(*) FROM tasks WHERE assignees_id = ?";
            PreparedStatement stmtAssign = conn.prepareStatement(queryAssign);
            stmtAssign.setInt(1, assigneeId);
            ResultSet rsAssign = stmtAssign.executeQuery();
            if (rsAssign.next()) {
                int taskAssignCount = rsAssign.getInt(1);
                taskAssignLabel.setText(String.valueOf(taskAssignCount));
            }
            rsAssign.close();
            stmtAssign.close();

            // Task Overdue
            String queryOverdue = "SELECT COUNT(*) FROM tasks WHERE assignees_id = ? AND deadline < ?";
            PreparedStatement stmtOverdue = conn.prepareStatement(queryOverdue);
            stmtOverdue.setInt(1, assigneeId);
            stmtOverdue.setDate(2, java.sql.Date.valueOf(LocalDate.now()));
            ResultSet rsOverdue = stmtOverdue.executeQuery();
            if (rsOverdue.next()) {
                int overdueCount = rsOverdue.getInt(1);
                taskOverdueLabel.setText(String.valueOf(overdueCount));
            }
            rsOverdue.close();
            stmtOverdue.close();

            // Task In Progress
            String queryInProgress = "SELECT COUNT(DISTINCT st.tasks_id) " +
                                     "FROM status_tracks st " +
                                     "JOIN tasks t ON st.tasks_id = t.id " +
                                     "WHERE t.assignees_id = ? AND st.status = 'in progress'";
            PreparedStatement stmtProgress = conn.prepareStatement(queryInProgress);
            stmtProgress.setInt(1, assigneeId);
            ResultSet rsProgress = stmtProgress.executeQuery();
            if (rsProgress.next()) {
                int inProgressCount = rsProgress.getInt(1);
                taskInProgressLabel.setText(String.valueOf(inProgressCount));
            }
            rsProgress.close();
            stmtProgress.close();
            
            //user name dan email
            String userInformation = "SELECT id, name, email FROM assignees WHERE id= ?";
            PreparedStatement stmtInformation = conn.prepareStatement(userInformation);
            stmtInformation.setInt(1, assigneeId);
            ResultSet rsInformation = stmtInformation.executeQuery();
            if (rsInformation.next()){
                String name = rsInformation.getString("name");
                String email = rsInformation.getString("email");

                nameLabel.setText(": " + name);
                emailLabel.setText(": " + email);
            }
            rsInformation.close();
            stmtInformation.close();
            
            //total pointnya
            String queryPoints = 
                    "SELECT SUM(t.point) AS total_points " +
                    "FROM tasks t " +
                    "JOIN ( " +
                    "    SELECT st.tasks_id " +
                    "    FROM status_tracks st " +
                    "    JOIN ( " +
                    "        SELECT tasks_id, MAX(created_at) AS latest_time " +
                    "        FROM status_tracks " +
                    "        GROUP BY tasks_id " +
                    "    ) latest ON st.tasks_id = latest.tasks_id AND st.created_at = latest.latest_time " +
                    "    WHERE st.status = 'completed' " +
                    ") completed_tasks ON t.id = completed_tasks.tasks_id " +
                    "WHERE t.assignees_id = ?";

            PreparedStatement stmtPoints = conn.prepareStatement(queryPoints);
            stmtPoints.setInt(1, assigneeId);
            ResultSet rsPoints = stmtPoints.executeQuery();
            if (rsPoints.next()) {
                int totalPointsQuery = rsPoints.getInt("total_points");
                totalPoints.setText(": " + totalPointsQuery);
            }
            rsPoints.close();
            stmtPoints.close();
            
            //recent pointnnya
            String queryRecentPoints = 
                "SELECT * FROM ( " +
                "    SELECT t.name, t.point, recent_completed.created_at " +
                "    FROM tasks t " +
                "    JOIN ( " +
                "        SELECT st.tasks_id, st.created_at " +
                "        FROM status_tracks st " +
                "        JOIN ( " +
                "            SELECT tasks_id, MAX(created_at) AS latest_time " +
                "            FROM status_tracks " +
                "            GROUP BY tasks_id " +
                "        ) latest ON st.tasks_id = latest.tasks_id AND st.created_at = latest.latest_time " +
                "        WHERE st.status = 'completed' AND st.created_at >= ? " +
                "    ) recent_completed ON t.id = recent_completed.tasks_id " +
                "    WHERE t.assignees_id = ? " +
                "    ORDER BY recent_completed.created_at DESC " +
                ") AS recent_limited " +
                "LIMIT 5";

            PreparedStatement stmtRecent = conn.prepareStatement(queryRecentPoints);
            stmtRecent.setDate(1, java.sql.Date.valueOf(LocalDate.now().minusDays(7)));
            stmtRecent.setInt(2, assigneeId);
            ResultSet rsRecent = stmtRecent.executeQuery();

            StringBuilder recentText = new StringBuilder("<html>");
            boolean hasRecent = false;
            while (rsRecent.next()) {
                hasRecent = true;
                String taskName = rsRecent.getString("name");
                int point = rsRecent.getInt("point");
                LocalDateTime completedAt = rsRecent.getTimestamp("created_at").toLocalDateTime();
                recentText.append(taskName).append(" (+").append(point).append(" pts)").append("<br>");
            }
            recentText.append("</html>");
            recentPoints.setText(hasRecent ? recentText.toString() : "No Recent Points");
            rsRecent.close();
            stmtRecent.close();
            
            // RECENT ACTIVITY
            String queryRecentActivity = 
                "SELECT p.name AS project_name, t.name AS task_name, st.status, st.updated_at " +
                "FROM status_tracks st " +
                "JOIN tasks t ON st.tasks_id = t.id " +
                "JOIN projects p ON t.projects_id = p.id " +
                "JOIN ( " +
                "    SELECT tasks_id, MAX(updated_at) AS latest_time " +
                "    FROM status_tracks " +
                "    GROUP BY tasks_id " +
                ") latest ON st.tasks_id = latest.tasks_id AND st.updated_at = latest.latest_time " +
                "WHERE t.assignees_id = ? " +
                "ORDER BY st.updated_at DESC " +
                "LIMIT 6";

            PreparedStatement stmtRecentActivity = conn.prepareStatement(queryRecentActivity);
            stmtRecentActivity.setInt(1, assigneeId);
            ResultSet rsActivity = stmtRecentActivity.executeQuery();

            Component[] components = activityPanel.getComponents();
            // hapus row sebelunya (header - index 0 to 2)
            for (int i = components.length - 1; i >= 3; i--) {
                activityPanel.remove(components[i]);
            }

            while (rsActivity.next()) {
                activityPanelDetails = new JPanel();
                activityPanelDetails.setLayout(new GridLayout(1, 3)); 
                activityPanelDetails.setBorder(BorderFactory.createEmptyBorder(10, 10, 5, 10));
                activityPanelDetails.setOpaque(false);
                
                String projectName = rsActivity.getString("project_name");
                String taskName = rsActivity.getString("task_name");
                String status = rsActivity.getString("status");
                
                
                
                JLabel projectLabel = new JLabel(projectName);
                projectLabel.setHorizontalAlignment(SwingConstants.LEFT);
                
                JPanel taskPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0)); // Panel dengan layout tengah
                JLabel taskLabel = new JLabel(taskName); // Tidak perlu align, karena panel sudah center
                taskPanel.add(taskLabel);

                JLabel statusLabel = new JLabel("Changed to " + status);
                statusLabel.setHorizontalAlignment(SwingConstants.RIGHT);
                
                activityPanelDetails.add(projectLabel);
                activityPanelDetails.add(taskLabel);
                activityPanelDetails.add(statusLabel);
                
                for (Component comp : activityPanelDetails.getComponents()) {
                    if (comp instanceof JLabel) {
                        comp.setFont(new Font("Tahoma", Font.PLAIN, 18));
                    }
                }
                
                activityPanel.add(activityPanelDetails);
            }

            activityPanel.revalidate();
            activityPanel.repaint();

            rsActivity.close();
            stmtRecentActivity.close();

            conn.close();

        } catch (SQLException e) {
            e.printStackTrace();
       }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int userId = 1; // buat test, nanti dihilangin mainnya
                new DashboardUser(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator LineSidebar;
    private javax.swing.JSeparator LineSidebar1;
    private javax.swing.JLabel LogoArasaka;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel OverdueTask1;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JPanel TopUser1;
    private javax.swing.JPanel TotalTask1;
    private javax.swing.JPanel TotalUser1;
    private javax.swing.JLabel TxtArasaka;
    private javax.swing.JLabel TxtDashboard;
    private javax.swing.JLabel TxtLogout;
    private javax.swing.JLabel TxtProject;
    private javax.swing.JLabel TxtProjectManagement;
    private javax.swing.JLabel TxtSocialMedia;
    private javax.swing.JLabel TxtTask;
    private javax.swing.JPanel activityPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel recentActivityLabel;
    private javax.swing.JLabel recentPoints;
    private javax.swing.JLabel taskAssignLabel;
    private javax.swing.JLabel taskInProgressLabel;
    private javax.swing.JPanel taskInProgressPanel;
    private javax.swing.JLabel taskOverdueLabel;
    private javax.swing.JLabel totalPoints;
    private javax.swing.JLabel txt1;
    // End of variables declaration//GEN-END:variables
}
